package com.herolens.app.vision

import android.content.Context
import android.os.Build
import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import java.nio.FloatBuffer
import kotlin.math.exp

/**
 * Optional neural hero classifier generated by training/train_hero_classifier.py.
 *
 * The app remains usable when the model is absent: TemplateHeroDetector falls back
 * to the existing signature matcher. When the ONNX model is bundled, portrait crops
 * are classified locally. Batched inference keeps a quick scan to only a few model
 * executions rather than one execution for every hero slot and jittered crop.
 */
class OnnxHeroClassifier(context: Context) : AutoCloseable {
    private val environment: OrtEnvironment? = runCatching { OrtEnvironment.getEnvironment() }.getOrNull()
    private val labels: List<String> = runCatching {
        context.assets.open(LABEL_ASSET).bufferedReader().useLines { lines ->
            lines.map(String::trim).filter(String::isNotEmpty).toList()
        }
    }.getOrDefault(emptyList())
    // ONNX Runtime requires SessionOptions to outlive every session created from it.
    private val sessionOptions: OrtSession.SessionOptions? = runCatching {
        OrtSession.SessionOptions().apply {
            setIntraOpNumThreads(2)
            setInterOpNumThreads(1)
            setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
                runCatching { addNnapi() }
            }
        }
    }.getOrNull()
    private val session: OrtSession? = runCatching {
        val env = environment ?: error("ONNX Runtime unavailable")
        val options = sessionOptions ?: error("ONNX session options unavailable")
        val bytes = context.assets.open(MODEL_ASSET).use { it.readBytes() }
        require(bytes.size > 32_000) { "AI model is a placeholder" }
        env.createSession(bytes, options)
    }.getOrNull()

    val isAvailable: Boolean
        get() = session != null && labels.size >= 2

    val modelLabelCount: Int
        get() = labels.size

    fun classify(crop: CroppedImage, topK: Int = 5): List<HeroCandidate> =
        classifyBatch(listOf(crop), topK).firstOrNull().orEmpty()

    fun classifyBatch(crops: List<CroppedImage>, topK: Int = 5): List<List<HeroCandidate>> {
        if (crops.isEmpty()) return emptyList()
        val activeSession = session ?: return List(crops.size) { emptyList() }
        val env = environment ?: return List(crops.size) { emptyList() }
        val inputName = activeSession.inputNames.firstOrNull() ?: return List(crops.size) { emptyList() }
        val input = FloatArray(crops.size * CHANNELS * INPUT_SIZE * INPUT_SIZE)
        crops.forEachIndexed { batchIndex, crop ->
            cropToTensor(crop, input, batchIndex * CHANNELS * INPUT_SIZE * INPUT_SIZE)
        }
        val shape = longArrayOf(crops.size.toLong(), CHANNELS.toLong(), INPUT_SIZE.toLong(), INPUT_SIZE.toLong())
        OnnxTensor.createTensor(env, FloatBuffer.wrap(input), shape).use { tensor ->
            val inputs: Map<String, OnnxTensor> = mapOf(inputName to tensor)
            activeSession.run(inputs).use { result ->
                val rows = extractRows(result[0].value)
                if (rows == null || rows.size != crops.size) return List(crops.size) { emptyList() }
                return rows.map { logits -> rank(logits, topK) }
            }
        }
    }

    private fun rank(logits: FloatArray, topK: Int): List<HeroCandidate> {
        if (logits.isEmpty()) return emptyList()
        val probabilities = softmax(logits)
        return probabilities.indices
            .asSequence()
            .filter { it < labels.size && labels[it] != UNKNOWN_LABEL }
            .map { index -> HeroCandidate(labels[index], probabilities[index]) }
            .sortedByDescending(HeroCandidate::confidence)
            .take(topK.coerceAtLeast(1))
            .toList()
    }

    private fun cropToTensor(crop: CroppedImage, output: FloatArray, outputOffset: Int) {
        val srcWidth = crop.width.coerceAtLeast(1)
        val srcHeight = crop.height.coerceAtLeast(1)
        val plane = INPUT_SIZE * INPUT_SIZE
        for (y in 0 until INPUT_SIZE) {
            val sourceY = ((y + 0.5f) * srcHeight / INPUT_SIZE).toInt().coerceIn(0, srcHeight - 1)
            for (x in 0 until INPUT_SIZE) {
                val sourceX = ((x + 0.5f) * srcWidth / INPUT_SIZE).toInt().coerceIn(0, srcWidth - 1)
                val source = (sourceY * srcWidth + sourceX) * 4
                val target = outputOffset + y * INPUT_SIZE + x
                val r = (crop.rgba[source].toInt() and 0xff) / 255f
                val g = (crop.rgba[source + 1].toInt() and 0xff) / 255f
                val b = (crop.rgba[source + 2].toInt() and 0xff) / 255f
                output[target] = (r - 0.485f) / 0.229f
                output[target + plane] = (g - 0.456f) / 0.224f
                output[target + plane * 2] = (b - 0.406f) / 0.225f
            }
        }
    }

    private fun extractRows(value: Any?): List<FloatArray>? = when (value) {
        is FloatArray -> listOf(value)
        is Array<*> -> value.mapNotNull { row ->
            when (row) {
                is FloatArray -> row
                is Array<*> -> row.firstOrNull() as? FloatArray
                else -> null
            }
        }.takeIf { it.isNotEmpty() }
        else -> null
    }

    private fun softmax(logits: FloatArray): FloatArray {
        val max = logits.maxOrNull() ?: 0f
        val output = FloatArray(logits.size)
        var sum = 0.0
        for (index in logits.indices) {
            val value = exp((logits[index] - max).toDouble())
            output[index] = value.toFloat()
            sum += value
        }
        if (sum <= 0.0) return output
        for (index in output.indices) output[index] = (output[index] / sum).toFloat()
        return output
    }

    override fun close() {
        runCatching { session?.close() }
        runCatching { sessionOptions?.close() }
    }

    private companion object {
        const val MODEL_ASSET = "model/hero_classifier.onnx"
        const val LABEL_ASSET = "model/hero_labels.txt"
        const val UNKNOWN_LABEL = "__unknown__"
        const val INPUT_SIZE = 96
        const val CHANNELS = 3
    }
}
